// Auto-generated from provided list of White Spark sources.
// Split into two arrays: races and skills.

export const WHITE_SPARK_RACES: string[] = [
  'Asahi Hai Futurity Stakes',
  'Hanshin Juvenile Fillies',
  'Hopeful Stakes',
  'Oka Sho',
  'Satsuki Sho',
  'NHK Mile Cup',
  'Japanese Oaks',
  'Tokyo Yushun (Japanese Derby)',
  'Yasuda Kinen',
  'Takarazuka Kinen',
  'Japan Dirt Derby',
  'Sprinters Stakes',
  'Kikuka Sho',
  'Shuka Sho',
  'Tenno Sho (Autumn)',
  'JBC Classic',
  "JBC Ladies' Classic",
  'JBC Sprint',
  'Queen Elizabeth II Cup',
  'Japan Cup',
  'Mile Championship',
  'Champions Cup',
  'Arima Kinen',
  'Tokyo Daishoten',
  'Kawasaki Kinen',
  'February Stakes',
  'Osaka Hai',
  'Takamatsunomiya Kinen',
  'Tenno Sho (Spring)',
  'Victoria Mile',
  'Teio Sho',
]

export const WHITE_SPARK_SKILLS: string[] = [
  'Right-Handed',
  'Left-Handed',
  'Tokyo Racecourse',
  'Nakayama Racecourse',
  'Hanshin Racecourse',
  'Kyoto Racecourse',
  'Chukyo Racecourse',
  'Sapporo Racecourse',
  'Hakodate Racecourse',
  'Fukushima Racecourse',
  'Niigata Racecourse',
  'Kokura Racecourse',
  'Standard Distance',
  'Non-Standard Distance',
  'Firm Conditions',
  'Wet Conditions',
  'Spring Runner',
  'Summer Runner',
  'Fall Runner',
  'Winter Runner',
  'Sunny Days',
  'Cloudy Days',
  'Rainy Days',
  'Snowy Days',
  'Inner Post Proficiency',
  'Inner Post Averseness',
  'Outer Post Proficiency',
  'Outer Post Averseness',
  'Maverick',
  'Competitive Spirit',
  'Wallflower',
  'Target in Sight',
  'Long Shot',
  'G1 Averseness',
  'Paddock Fright',
  'Professor of Curvature',
  'Corner Adept',
  'Corner Connoisseur',
  'Corner Acceleration',
  'Swinging Maestro',
  'Corner Recovery',
  'Beeline Burst',
  'Straightaway Adept',
  'Rushing Gale!',
  'Straightaway Acceleration',
  'Breath of Fresh Air',
  'Straightaway Recovery',
  'Ramp Revulsion',
  'Packphobia',
  'Defeatist',
  'Reckless',
  'Concentration',
  'Focus',
  'Gatekept',
  'Iron Will',
  'Lay Low',
  'Center Stage',
  'Prudent Positioning',
  "It's On!",
  'Ramp Up',
  'Indomitable',
  'Pace Strategy',
  'Unruffled',
  'Calm in a Crowd',
  'No Stopping Me!',
  'Nimble Navigator',
  'Lane Legerdemain',
  'Go with the Flow',
  'In Body and Mind',
  'Homestretch Haste',
  'Running Idle',
  'Taking the Lead',
  'Early Lead',
  'Escape Artist',
  'Fast-Paced',
  'Unrestrained',
  'Final Push',
  'Calm and Collected',
  'Stamina to Spare',
  'Race Planner',
  'Preferred Position',
  'Speed Star',
  'Prepared to Pass',
  'Fast & Furious',
  'Position Pilfer',
  'On Your Left!',
  'Slick Surge',
  'Rising Dragon',
  'Outer Swell',
  'Sleeping Lion',
  'Standing By',
  'Sturm und Drang',
  'Masterful Gambit',
  'Encroaching Shadow',
  'Straightaway Spurt',
  'Turbo Sprint',
  'Sprinting Gear',
  'Wait-and-See',
  'Blinding Flash',
  'Gap Closer',
  'Mile Maven',
  'Productive Plan',
  'Keen Eye',
  'Watchful Eye',
  'Furious Feat',
  'Updrafters',
  'Trackblazer',
  'Rosy Outlook',
  'Killer Tunes',
  'Up-Tempo',
  'Unyielding',
  'Steadfast',
  'Cooldown',
  'Deep Breaths',
  'Innate Experience',
  'Inside Scoop',
  'Adrenaline Rush',
  'Extra Tank',
  'Trick (Front)',
  'Trick (Rear)',
  'Frenzied Front Runners',
  'Frenzied Pace Chasers',
  'Frenzied Late Surgers',
  'Frenzied End Closers',
  'Subdued Front Runners',
  'Flustered Front Runners',
  'Hesitant Front Runners',
  'Subdued Pace Chasers',
  'Flustered Pace Chasers',
  'Hesitant Pace Chasers',
  'Subdued Late Surgers',
  'Flustered Late Surgers',
  'Hesitant Late Surgers',
  'Subdued End Closers',
  'Flustered End Closers',
  'Hesitant End Closers',
  'Oi Racecourse',
  'Sprint Straightaways',
  'Sprint Corners',
  'Staggering Lead',
  'Huge Lead',
  'Plan X',
  'Countermeasure',
  'Perfect Prep!',
  'Meticulous Measures',
  'Intimidate',
  "You've Got No Shot",
  'Stop Right There!',
  'Mile Straightaways',
  'Mile Corners',
  'Changing Gears',
  'Shifting Gears',
  'Step on the Gas!',
  'Acceleration',
  'Big-Sisterly',
  'Unyielding Spirit',
  'Greed for Speed',
  'Speed Eater',
  'Battle Formation',
  'Opening Gambit',
  'Medium Straightaways',
  'Medium Corners',
  'Clairvoyance',
  'Hawkeye',
  'Lightning Step',
  'Thunderbolt Step',
  'Miraculous Step',
  'Soft Step',
  'Dominator',
  'Tether',
  'Mystifying Murmur',
  'Murmur',
  'Long Straightaways',
  'Long Corners',
  'Vanguard Spirit',
  'Keeping the Lead',
  'Passing Pro',
  'Overwhelming Pressure',
  'Pressure',
  'Stamina Siphon',
  'Stamina Eater',
  'Illusionist',
  'Smoke Screen',
  'Front Runner Straightaways',
  'Front Runner Corners',
  'Dodging Danger',
  "Leader's Pride",
  'Restless',
  'Moxie',
  'Reignition',
  'Second Wind',
  'Restart',
  'Pace Chaser Straightaways',
  'Pace Chaser Corners',
  'Technician',
  'Shrewd Step',
  'Determined Descent',
  'Straight Descent',
  'Gourmand',
  'Hydrate',
  'Shatterproof',
  'Tactical Tweak',
  'Dazzling Disorientation',
  'Disorient',
  'Late Surger Straightaways',
  'Later Surger Corners',
  'Late Surger Corners',
  'Hard Worker',
  'Fighter',
  '15,000,000 CC',
  '1,500,000 CC',
  'Relax',
  'A Small Breather',
  'The Bigger Picture',
  'Studious',
  'All-Seeing Eyes',
  'Sharp Gaze',
  'End Closer Straightaways',
  'End Closer Corners',
  'The Coast Is Clear!',
  'I Can See Right Through You',
  'Go-Home Specialist',
  'After-School Stroll',
  'Serenity',
  'Levelheaded',
  'Crusader',
  'Strategist',
  'Petrifying Gaze',
  'Intense Gaze',
  'Front Runner Savvy',
  'Pace Chaser Savvy',
  'Late Surger Savvy',
  'End Closer Savvy',
  'Super Lucky Seven',
  'Lucky Seven',
  'Triple 7s',
  'Highlander',
  'Uma Stan',
  'Groundwork',
  'Tail Held High',
  'Shake It Out',
  'Sympathy',
  'Lone Wolf',
  'Slipstream',
  "Playtime's Over!",
]

export default {
  WHITE_SPARK_RACES,
  WHITE_SPARK_SKILLS,
}
